-- AlterTable
ALTER TABLE "User" ADD COLUMN     "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "permissions" TEXT[] DEFAULT ARRAY['MANAGE_USERS', 'DELETE_ITEMS', 'EDIT_ITEMS', 'ADJUST_STOCK']::TEXT[];
